export type Resource = {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  publishedAt: string;
  featured?: boolean;
  downloadUrl?: string;
  // HTML content generated by Claude - rendered using dangerouslySetInnerHTML
  // SECURITY NOTE: Only use this with trusted content (e.g., content you generate yourself)
  // Never use with user-submitted content as it can enable XSS attacks
  contentHtml?: string;
};

export const resources: Resource[] = [
  {
    id: "11",
    slug: "notebooklm-claude-code-automation-guide",
    title: "NotebookLM + Claude Automation",
    description:
      "Build an automated research pipeline connecting Claude Code to Google's NotebookLM. Scrape YouTube, generate analysis, and create infographics with a single command.",
    category: "Automations",
    publishedAt: "2026-04-03",
    featured: true,
    downloadUrl: "/downloads/notebooklm-claude-code-automation-guide.pdf",
    contentHtml: `
      <div class="space-y-8">
        <p class="text-lg text-zinc-300 leading-relaxed">
          This pipeline connects <span class="text-[#FF6A25] font-semibold">Claude Code</span> to Google's NotebookLM via an unofficial Python API (notebooklm-py). Give it a topic → it scrapes YouTube → pushes videos to NotebookLM → generates deep analysis, infographics, podcasts, and study guides automatically.
        </p>
        <p class="text-zinc-500 text-sm leading-relaxed">
          Original system by Steve Arneson (stevearneson.com/notebook) · Python library by Teng Lin (github.com/teng-lin/notebooklm-py)
        </p>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-4">Key Capabilities</h3>
        <ul class="list-disc list-inside space-y-2 text-zinc-400 ml-4 mb-6">
          <li><strong class="text-zinc-300">YouTube Research:</strong> Automated scraping of metadata (titles, views, author, duration, URLs) on any topic</li>
          <li><strong class="text-zinc-300">Cross-Source Analysis:</strong> NotebookLM processes all sources at once for deep cross-referencing and pattern detection</li>
          <li><strong class="text-zinc-300">Podcast Briefings:</strong> Auto-generated audio overviews and summaries you can listen to on the go</li>
          <li><strong class="text-zinc-300">Visual Deliverables:</strong> Infographics, slide decks, flashcards, and study guides on demand</li>
        </ul>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-4">Use Cases for Agency Owners</h3>
        <ul class="list-disc list-inside space-y-2 text-zinc-400 ml-4 mb-6">
          <li>Competitive intelligence on client industries</li>
          <li>Market research for proposals and pitches</li>
          <li>Content trend analysis for social media strategies</li>
          <li>Client onboarding research</li>
          <li>Staying ahead of industry shifts</li>
        </ul>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-4">Prerequisites — You Need 2 Things</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <div class="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
            <p class="text-[#FF6A25] font-semibold text-sm mb-2">Claude Code (Pro or Max)</p>
            <p class="text-zinc-400 text-sm">Download at claude.ai/download. Free plan won't work — you need Pro ($20/mo) or Max. Claude Code handles all installs including Python.</p>
          </div>
          <div class="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
            <p class="text-[#FF6A25] font-semibold text-sm mb-2">Google Account + NotebookLM</p>
            <p class="text-zinc-400 text-sm">NotebookLM is free at notebooklm.google.com. Sign in once to confirm your account works before running setup.</p>
          </div>
        </div>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-3">Step 1 — Paste This Into Claude Code</h3>
        <p class="text-zinc-400 mb-4">This single prompt builds the YouTube research skill, installs NotebookLM-PY, and wires everything together. No other files needed. <strong class="text-zinc-300">Copy the entire block and paste it into Claude Code.</strong></p>

        <div class="relative bg-[#121212] rounded-xl p-5 my-6 font-mono text-sm text-zinc-200 overflow-x-auto">
          <pre><code>I want to set up an automated research pipeline connecting Claude Code to
NotebookLM. Please perform the following steps and I will 'accept' all
your proposed changes:

1. Build a YouTube Research Skill: Create a custom Python-based skill
   using the yt-dlp dependency. This skill should be able to scrape
   YouTube metadata, including video titles, views, author, duration,
   and URLs based on a search query.

2. Integrate NotebookLM-PY: I want to use the unofficial Python API for
   NotebookLM created by Teng Lin. Repository:
   https://github.com/teng-lin/notebooklm-py
   Install necessary packages and set up a skill to:
   - Create new notebooks
   - Upload YouTube URLs as sources
   - Request analysis and deliverables like infographics, slide decks,
     and flashcards

3. Guide me through Authentication: Once the tools are installed, remind
   me to open a separate terminal window to run the notebooklm login
   command so I can authenticate with my Google account.

4. Confirm Readiness: Once everything is installed and the skills are
   recognized, let me know you are ready for a test run.

The goal is that once finished, I should be able to give a single command
like: "Use the yt-research skill to find the 25 latest trending videos on
[YOUR TOPIC]. Once we have those videos, send them over to NotebookLM
using the notebooklm skill. Give me its analysis on top findings, then
have NotebookLM create an infographic in a handwritten/chalkboard style."

Important: If I give the research command without specifying a topic,
ask me what topic I want to research before proceeding.</code></pre>
        </div>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-4">The 4-Step Workflow (After Pasting)</h3>
        <ol class="list-decimal pl-6 space-y-4 text-zinc-400">
          <li><strong class="text-zinc-300">Accept Everything:</strong> Claude Code writes Python scripts and creates skills. When it asks permission to run commands or install packages, hit Y or Enter. If Python isn't installed, Claude Code handles that too.</li>
          <li><strong class="text-zinc-300">Authenticate (Separate Terminal):</strong> When Claude tells you to authenticate, open a COMPLETELY SEPARATE terminal window — not inside Claude Code. Run <code class="text-[#FF6A25] bg-zinc-900 px-1.5 py-0.5 rounded text-xs">notebooklm login</code> → browser opens → log into Google → done. See the Login Fix section below for the full tested process.</li>
          <li><strong class="text-zinc-300">Claude Confirms Ready:</strong> Claude Code tells you skills are installed and recognized. It will ask for your research topic, or you can jump straight to the research command.</li>
          <li><strong class="text-zinc-300">Run Your First Research:</strong> Give Claude Code the research command. It scrapes YouTube, pushes videos to NotebookLM, analyzes findings, and generates your deliverable.</li>
        </ol>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-3">Step 2 — Run Your First Research Command</h3>
        <p class="text-zinc-400 mb-4">Once setup is confirmed, give Claude Code this command. Replace <code class="text-[#FF6A25] bg-zinc-900 px-1 rounded text-xs">[YOUR TOPIC]</code> with your research subject.</p>

        <div class="relative bg-[#121212] rounded-xl p-5 my-6 font-mono text-sm text-zinc-200 overflow-x-auto">
          <pre><code>Use the yt-research skill to find the 25 latest trending videos on
[YOUR TOPIC]. Once we have those videos, send them over to NotebookLM
using the notebooklm skill. Give me its analysis on the top findings,
then have NotebookLM create an infographic in a handwritten / chalkboard
style depicting that analysis.</code></pre>
        </div>

        <blockquote class="border-l-2 border-[#FF6A25] bg-zinc-900/50 p-4 my-6 text-zinc-300">
          <strong class="text-[#FF6A25]">Pro Tip:</strong> Replace [YOUR TOPIC] with anything: "AI avatar content for health coaches", "competitor analysis for Shopify stores", "latest trends in social media marketing India". If you forget the topic, Claude will ask.
        </blockquote>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-3">NotebookLM Login — The Working Method</h3>
        <p class="text-zinc-400 mb-4">The original guide's login instructions are incomplete. The basic pip install doesn't include browser support needed for login. Here's the <span class="text-[#FF6A25] font-semibold">full tested process that actually works:</span></p>

        <div class="relative bg-[#121212] rounded-xl p-5 my-6 font-mono text-sm text-zinc-200 overflow-x-auto">
          <pre><code># Step 1: Install with browser support (critical — do NOT skip [browser])
pip install "notebooklm-py[browser]"

# Step 2: Install Chromium for Playwright
playwright install chromium
# If this fails with TypeError, run first:
#   playwright install-deps chromium

# Step 3: Open a FRESH SEPARATE terminal (NOT inside Claude Code)
#   Mac: Cmd+Space → type Terminal → Enter
#   Windows: Win+R → type cmd → Enter

# Step 4: Login
notebooklm login
# Browser opens → log in with Google → wait for SUCCESS message
# For Edge SSO orgs: notebooklm login --browser msedge

# Step 5: Verify
notebooklm auth check --test
notebooklm list    # Should show notebooks or empty list
# If "Unauthorized" → re-run login

# Session saved at ~/.notebooklm/storage_state.json
# Sessions expire every 1–2 weeks — re-run login when needed</code></pre>
        </div>

        <blockquote class="border-l-2 border-[#FF6A25] bg-zinc-900/50 p-4 my-6 text-zinc-300">
          <strong class="text-[#FF6A25]">Key Insight:</strong> Playwright is ONLY needed for the <code class="text-zinc-300 bg-zinc-800 px-1 rounded text-xs">notebooklm login</code> command. Every other operation uses standard HTTP. You can copy a valid <code class="text-zinc-300 bg-zinc-800 px-1 rounded text-xs">~/.notebooklm/storage_state.json</code> to servers without installing Playwright there.
        </blockquote>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-4">Troubleshooting</h3>
        <div class="overflow-x-auto rounded-xl border border-zinc-800 mb-6">
          <table class="w-full text-sm">
            <thead>
              <tr class="bg-zinc-900 border-b border-zinc-800">
                <th class="text-left px-4 py-3 text-zinc-300 font-semibold w-1/3">Problem</th>
                <th class="text-left px-4 py-3 text-zinc-300 font-semibold">Solution</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-zinc-800/50">
              <tr>
                <td class="px-4 py-3 text-zinc-400">Browser doesn't open on login</td>
                <td class="px-4 py-3 text-zinc-400">Run in a fresh terminal (not Claude Code). Ensure pip install "notebooklm-py[browser]" and playwright install chromium completed.</td>
              </tr>
              <tr class="bg-zinc-900/30">
                <td class="px-4 py-3 text-zinc-400">Install fails with errors</td>
                <td class="px-4 py-3 text-zinc-400">Paste exact error into Claude Code. It diagnoses and fixes automatically. Keep accepting changes.</td>
              </tr>
              <tr>
                <td class="px-4 py-3 text-zinc-400">Skills not recognized</td>
                <td class="px-4 py-3 text-zinc-400">Ask Claude Code: "Can you verify the yt-research and notebooklm skills are installed?" Also run: notebooklm skill status</td>
              </tr>
              <tr class="bg-zinc-900/30">
                <td class="px-4 py-3 text-zinc-400">Rate limit / infographic fails</td>
                <td class="px-4 py-3 text-zinc-400">Wait 5 min and retry. Use: notebooklm generate audio --retry 3. Add 2s delays between URL additions.</td>
              </tr>
              <tr>
                <td class="px-4 py-3 text-zinc-400">Unauthorized / redirect errors</td>
                <td class="px-4 py-3 text-zinc-400">Cookies expired (1–2 weeks). Re-run: notebooklm login then notebooklm auth check --test</td>
              </tr>
              <tr class="bg-zinc-900/30">
                <td class="px-4 py-3 text-zinc-400">Google blocking automation</td>
                <td class="px-4 py-3 text-zinc-400">Debug: NOTEBOOKLM_DEBUG_RPC=1 notebooklm list. If RPC IDs changed, report on GitHub.</td>
              </tr>
              <tr>
                <td class="px-4 py-3 text-zinc-400">Audio/video silently fails</td>
                <td class="px-4 py-3 text-zinc-400">Use: notebooklm generate audio --wait. Or poll: notebooklm artifact poll &lt;task_id&gt;. Retry usually works.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <h3 class="text-xl font-bold text-zinc-50 mt-8 mb-4">NotebookLM CLI Cheat Sheet</h3>
        <div class="relative bg-[#121212] rounded-xl p-5 my-6 font-mono text-sm text-zinc-200 overflow-x-auto">
          <pre><code># ── Authentication ──────────────────────────────────────────
notebooklm login                           # Browser login
notebooklm login --browser msedge          # Edge for SSO orgs
notebooklm auth check --test               # Verify auth

# ── Notebook Management ─────────────────────────────────────
notebooklm list                            # List all notebooks
notebooklm create "My Research"            # Create notebook
notebooklm use &lt;notebook_id&gt;              # Select active
notebooklm metadata --json                 # Export metadata

# ── Sources ─────────────────────────────────────────────────
notebooklm source add "https://..."        # Add URL
notebooklm source add "./paper.pdf"        # Add local file
notebooklm source add-research "AI"        # Web research + import

# ── Chat &amp; Analysis ─────────────────────────────────────────
notebooklm ask "Key themes?"               # Chat with sources
notebooklm ask "Summarize" --sources s1    # Query specific sources

# ── Generate Deliverables ───────────────────────────────────
notebooklm generate audio                  # Podcast overview
notebooklm generate audio --retry 3        # Auto-retry
notebooklm generate audio --wait           # Wait for completion
notebooklm generate video --retry 5        # Video overview
notebooklm artifact poll &lt;task_id&gt;       # Poll status

# ── Agent Skills ────────────────────────────────────────────
notebooklm agent show claude               # Claude skill template
notebooklm agent show codex                # Codex instructions
notebooklm skill status                    # Check installation

# ── Debug ───────────────────────────────────────────────────
NOTEBOOKLM_LOG_LEVEL=INFO notebooklm list     # Info logging
NOTEBOOKLM_LOG_LEVEL=DEBUG notebooklm list    # Full debug
NOTEBOOKLM_DEBUG_RPC=1 notebooklm list        # Check RPC IDs</code></pre>
        </div>

        <blockquote class="border-l-2 border-zinc-600 bg-zinc-900/50 p-4 my-6 text-zinc-400 text-sm">
          <strong class="text-zinc-300">Important Disclaimer:</strong> NotebookLM-PY uses undocumented Google APIs that can change without notice. This is a community project, not affiliated with Google. Best for prototypes, research, and personal projects. APIs may break if Google changes internal endpoints.
        </blockquote>

      </div>
    `,
  },
];

// Categories for filtering
export const categories = [
  "All",
  "Prompts",
  "Tools",
  "Video Editing",
  "Automations",
  "Marketing",
  "Learning",
];

// Helper functions
export function getAllResources(): Resource[] {
  return resources.sort(
    (a, b) =>
      new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
  );
}

export function getFeaturedResources(): Resource[] {
  return resources.filter((r) => r.featured).slice(0, 6);
}

export function getResourceBySlug(slug: string): Resource | undefined {
  return resources.find((r) => r.slug === slug);
}

export function getRelatedResources(currentSlug: string, category: string, limit: number = 3): Resource[] {
  return resources
    .filter((r) => r.slug !== currentSlug)
    .filter((r) => r.category === category)
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit);
}
